INSERT INTO reglas_clinica (seccion, titulo, items) VALUES
('financieras', 'Reglas Financieras', '["Costo por sesión: $750 MXN (tarifa única para todos los pacientes)","Distribución del pago: 50% Psicóloga / 25% Propietario / 25% Supervisora","Gastos fijos mensuales: $180,000 MXN (renta, servicios, nómina administrativa)","Meta de ocupación: 100% — 1,100 sesiones/mes (275/semana)","Facturación: Todos los gastos de caja chica y entregas de dinero requieren factura/comprobante","Firma digital: Requerida para autorizar gastos y entregas de dinero (password)","Autorización: Solo supervisora/líder puede autorizar gastos y entregas"]'),
('sesiones', 'Reglas de Sesiones y Programas', '["Duración del programa: 12 a 16 sesiones por programa terapéutico","Confirmación doble: La psicóloga confirma la sesión → se crea cobro automático en recepción con estado confirmado por psicóloga","Detección de desviaciones: El sistema detecta retrasos, saltos de meta, repeticiones y sesiones fuera de programa","Recordatorio automático: Se envía correo 24h antes de cada sesión con fecha y recordatorio de pago ($750 MXN)","Corte de caja: Diario al cerrar recepción","Entregas de dinero: Solicitante y receptor no pueden ser la misma persona"]'),
('accesos', 'Reglas de Acceso y Roles', '["Psicóloga: Solo ve SUS pacientes asignados. No accede a Dashboard, Recepción, Mercadeo, Talleres ni Admin","Supervisora/Líder: Acceso total. Ve todos los pacientes, puede agregar comentarios visibles para la psicóloga","Recepcionista: Solo accede a Recepción (cobros, entregas, caja chica, citas)","Mercadeo y Talleres: Solo accesibles por supervisora/líder","Biometría: Login por huella digital (WebAuthn) disponible para acceso rápido","Contraseña por psicóloga: Cada psicóloga tiene su propio login para acceder a su panel"]'),
('evaluacion', 'Reglas de Evaluación', '["Cuestionario inicial: 123 preguntas en 13 secciones — aplica a TODOS los pacientes nuevos","Trastornos alimenticios: Incluye screening psicológico de trastornos de la conducta alimentaria","Dictado por voz: Disponible en todas las notas clínicas (Web Speech API, es-MX)","Fotografía: Se captura foto del paciente al registrar (cámara integrada)","Archivos permitidos: PDF, DOC, DOCX, JPG, JPEG, PNG para evaluaciones y facturas"]'),
('asignacion', 'Asignación y Tratamiento', '["Una psicóloga por paciente: Cada paciente es asignado a UNA psicóloga por programa activo","Múltiples tratamientos: Un paciente puede tener varios programas asignados (ansiedad + pareja, etc.)","Progreso: Se mide por sesiones completadas / total del programa (barra de progreso visible)","Estados: Activo, inactivo, completado. Solo pacientes activos ven en panel de psicóloga"]'),
('derechos', 'Derechos del Paciente', '["Confidencialidad: La información clínica solo es accesible para su psicóloga, supervisora y recepcionista (cobros)","Historial clínico: El paciente tiene acceso a ver su historial completo de sesiones y notas","Reprogramación: Puede reprogramar sesiones con anticipación razonable","Recordatorios: Recibe correo de recordatorio 24h antes de cada sesión con costo","Evaluación inicial: Se realiza cuestionario completo al iniciar tratamiento (123 preguntas)"]'),
('obligaciones', 'Obligaciones del Paciente', '["Pago puntual: $750 MXN por sesión, debe pagarse antes o el día de la sesión","Asistencia: Cancelar con al menos 24h de anticipación. No presentarse sin aviso afecta el tratamiento","Compromiso: Completar el programa completo (12-16 sesiones) para mejores resultados","Veracidad: Proporcionar información veraz en el cuestionario inicial y durante el tratamiento"]'),
('flujo', 'Flujo del Paciente', '["1. Registro: Recepcionista registra datos personales, motivo de consulta y captura foto","2. Cuestionario: Paciente completa 123 preguntas de evaluación inicial","3. Asignación: Supervisora asigna psicóloga, programa y supervisor","4. Tratamiento: 12-16 sesiones con seguimiento, notas y confirmación doble","5. Seguimiento: Supervisora monitorea progreso, agrega comentarios y detecta desviaciones","6. Alta: Programa completado. Paciente pasa a historial"]'),
('principios', 'Principios y Valores de la Compañía', '["Confidencialidad absoluta: la información de cada paciente es privada, protegida y jamás se comparte","Ética profesional: actuamos con integridad, honestidad y responsabilidad en todo momento","Empatía y calidez: tratamos a cada persona con dignidad, respeto y comprensión","Excelencia en el servicio: mejora continua en la calidad de sesiones, atención e instalaciones","Compromiso con el bienestar: el bienestar del paciente es nuestra prioridad absoluta","Transparencia: información clara y honesta sobre precios, horarios y procesos","Ambiente seguro y limpio: instalaciones limpias, ordenadas, accesibles y en buen estado","Trabajo en equipo: colaboración y comunicación respetuosa entre psicólogas, supervisora y recepción"]');
